# Generated by Django 5.2 on 2025-05-10 18:17

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='token',
            field=models.CharField(default=App.models.generate_unique_token, max_length=3, unique=True),
        ),
    ]
